import { APP_ENTRANCE_S } from "@/components/session/intro/intro-constants";

export type IntroAppAccent = "nova" | "bite" | "frame" | "apex";

export type IntroAppConfig = {
  id: string;
  label: string;
  accent: IntroAppAccent;
  enterAt: number;
  imageSrc: string;
  imageAlt: string;
  desktop: { x: string; y: string; rotate: number; scale: number; z: number };
  mobile: { x: string; y: string; rotate: number; scale: number; z: number };
  entrance: {
    fromX: string;
    fromY: string;
    fromRotate: number;
    glow: string;
  };
};

export const INTRO_CINEMATIC_APPS: IntroAppConfig[] = [
  {
    id: "nova",
    label: "NOVA",
    accent: "nova",
    enterAt: APP_ENTRANCE_S.nova,
    imageSrc: "/intro/nova.png",
    imageAlt: "Nova fashion store generated by Vodex",
    desktop: { x: "-30%", y: "-26%", rotate: -5, scale: 0.96, z: 12 },
    mobile: { x: "-30%", y: "-30%", rotate: -4, scale: 0.78, z: 12 },
    entrance: { fromX: "-115%", fromY: "0%", fromRotate: -12, glow: "purple" },
  },
  {
    id: "bite",
    label: "bite.",
    accent: "bite",
    enterAt: APP_ENTRANCE_S.bite,
    imageSrc: "/intro/bite.png",
    imageAlt: "Bite food delivery app generated by Vodex",
    desktop: { x: "30%", y: "-24%", rotate: 4, scale: 0.94, z: 14 },
    mobile: { x: "30%", y: "-30%", rotate: 3, scale: 0.76, z: 14 },
    entrance: { fromX: "115%", fromY: "0%", fromRotate: 10, glow: "orange" },
  },
  {
    id: "frame",
    label: "FRAME AI",
    accent: "frame",
    enterAt: APP_ENTRANCE_S.frame,
    imageSrc: "/intro/frame-ai.png",
    imageAlt: "Frame AI video editor generated by Vodex",
    desktop: { x: "-28%", y: "28%", rotate: 3, scale: 0.92, z: 16 },
    mobile: { x: "-30%", y: "30%", rotate: 2, scale: 0.74, z: 16 },
    entrance: { fromX: "-75%", fromY: "85%", fromRotate: 7, glow: "cyan" },
  },
  {
    id: "apex",
    label: "Apex Finance",
    accent: "apex",
    enterAt: APP_ENTRANCE_S.apex,
    imageSrc: "/intro/apex.png",
    imageAlt: "Apex Finance dashboard generated by Vodex",
    desktop: { x: "28%", y: "26%", rotate: -4, scale: 0.95, z: 18 },
    mobile: { x: "30%", y: "30%", rotate: -3, scale: 0.75, z: 18 },
    entrance: { fromX: "75%", fromY: "85%", fromRotate: -9, glow: "green" },
  },
];
