import type { MobileAppConfig } from "@/lib/mobile/types";

export type CapacitorProjectFiles = Array<{ path: string; content: string }>;

export function generateCapacitorWrapperProject(input: {
  config: Partial<MobileAppConfig>;
  webUrl: string;
  appFiles: Array<{ path: string; content: string }>;
  billingConfigJson?: string | null;
}): CapacitorProjectFiles {
  const appId = input.config.package_id ?? input.config.bundle_id ?? "com.vodex.app";
  const appName = input.config.app_name ?? "Dream App";
  const shortName = input.config.short_name ?? appName.slice(0, 12);
  const theme = input.config.theme_color ?? "#6366f1";
  const splashMs =
    typeof input.config.splash_duration_ms === "number" && input.config.splash_duration_ms > 0
      ? input.config.splash_duration_ms
      : 2000;
  const storeDraft =
    input.config.store_draft && typeof input.config.store_draft === "object"
      ? (input.config.store_draft as Record<string, unknown>)
      : {};
  const sha256List = Array.isArray(storeDraft.play_sha256_fingerprints)
    ? (storeDraft.play_sha256_fingerprints as string[]).filter(Boolean)
    : [];
  const sha256Fingerprints =
    sha256List.length > 0 ? sha256List : ["REPLACE_WITH_YOUR_SHA256_FINGERPRINT"];

  const permissions = input.config.permissions ?? {};
  const androidPermissions: string[] = [];
  if (permissions.camera) androidPermissions.push("android.permission.CAMERA");
  if (permissions.photos) androidPermissions.push("android.permission.READ_MEDIA_IMAGES");
  if (permissions.location) {
    androidPermissions.push("android.permission.ACCESS_FINE_LOCATION");
    androidPermissions.push("android.permission.ACCESS_COARSE_LOCATION");
  }
  if (permissions.microphone) androidPermissions.push("android.permission.RECORD_AUDIO");
  if (permissions.contacts) androidPermissions.push("android.permission.READ_CONTACTS");
  if (permissions.push_notifications) androidPermissions.push("android.permission.POST_NOTIFICATIONS");

  const files: CapacitorProjectFiles = [
    {
      path: "capacitor.config.ts",
      content: `import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: '${appId}',
  appName: '${appName.replace(/'/g, "\\'")}',
  webDir: 'dist',
  server: {
    url: '${input.webUrl}',
    cleartext: false,
  },
  plugins: {
    SplashScreen: {
      launchShowDuration: ${splashMs},
      backgroundColor: '${theme}',
      launchAutoHide: true,
    },
  },
};

export default config;
`,
    },
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: shortName.toLowerCase().replace(/\s+/g, "-"),
          private: true,
          scripts: {
            "cap:sync": "npx cap sync",
            "cap:android": "npx cap open android",
            "cap:ios": "npx cap open ios",
          },
          dependencies: {
            "@capacitor/core": "^6.0.0",
            "@capacitor/android": "^6.0.0",
            "@capacitor/ios": "^6.0.0",
            "@capacitor/splash-screen": "^6.0.0",
          },
          devDependencies: {
            "@capacitor/cli": "^6.0.0",
            typescript: "^5.0.0",
          },
        },
        null,
        2,
      ),
    },
    {
      path: "README-MOBILE-WRAP.md",
      content: `# ${appName} — Mobile wrapper

Generated by Vodex.

## Next steps

1. Run \`npm install\`
2. Place your web build in \`dist/\` (or update \`webDir\` in capacitor.config.ts)
3. Run \`npx cap sync\`
4. Open Android Studio: \`npx cap open android\`
5. Open Xcode (macOS): \`npx cap open ios\`

Version: ${input.config.version_name ?? "0.0.1"} (Android code ${input.config.android_version_code ?? 1}, iOS build ${input.config.ios_build_number ?? 1})

Package / Bundle: ${appId}

## Permissions declared
${androidPermissions.length ? androidPermissions.map((p) => `- ${p}`).join("\n") : "- None beyond defaults"}

Do not commit signing keys or store credentials to git.
`,
    },
    {
      path: "android-permissions.json",
      content: JSON.stringify({ permissions: androidPermissions }, null, 2),
    },
    ...(input.billingConfigJson
      ? [
          {
            path: "dreamos-billing.json",
            content: input.billingConfigJson,
          },
          {
            path: "android/app/src/main/assets/dreamos-billing.json",
            content: input.billingConfigJson,
          },
          {
            path: "ios/App/App/dreamos-billing.json",
            content: input.billingConfigJson,
          },
        ]
      : []),
  ];

  for (const f of input.appFiles.slice(0, 200)) {
    files.push({ path: `web-src/${f.path}`, content: f.content });
  }

  return files;
}

export function generateTwaManifest(input: {
  config: Partial<MobileAppConfig>;
  webUrl: string;
}): CapacitorProjectFiles {
  const appId = input.config.package_id ?? "com.vodex.app";
  const appName = input.config.app_name ?? "Dream App";
  const splashMs =
    typeof input.config.splash_duration_ms === "number" && input.config.splash_duration_ms > 0
      ? input.config.splash_duration_ms
      : 2000;
  const storeDraft =
    input.config.store_draft && typeof input.config.store_draft === "object"
      ? (input.config.store_draft as Record<string, unknown>)
      : {};
  const sha256List = Array.isArray(storeDraft.play_sha256_fingerprints)
    ? (storeDraft.play_sha256_fingerprints as string[]).filter(Boolean)
    : [];
  const sha256Fingerprints =
    sha256List.length > 0 ? sha256List : ["REPLACE_WITH_YOUR_SHA256_FINGERPRINT"];
  const host = (() => {
    try {
      return new URL(input.webUrl).host;
    } catch {
      return "example.com";
    }
  })();

  return [
    {
      path: "twa-manifest.json",
      content: JSON.stringify(
        {
          packageId: appId,
          host,
          name: appName,
          launcherName: input.config.short_name ?? appName,
          themeColor: input.config.theme_color ?? "#6366f1",
          startUrl: "/",
          iconUrl: input.config.icon_url ?? "",
          splashScreenFadeOutDuration: Math.min(1000, Math.max(200, Math.round(splashMs / 4))),
        },
        null,
        2,
      ),
    },
    {
      path: "assetlinks-template.json",
      content: JSON.stringify(
        [
          {
            relation: ["delegate_permission/common.handle_all_urls"],
            target: {
              namespace: "android_app",
              package_name: appId,
              sha256_cert_fingerprints: sha256Fingerprints,
            },
          },
        ],
        null,
        2,
      ),
    },
    {
      path: "README-TWA.md",
      content: `# Trusted Web Activity wrapper

Host: ${host}
Package: ${appId}

1. Host \`assetlinks.json\` at https://${host}/.well-known/assetlinks.json
2. Replace SHA-256 fingerprint in assetlinks-template.json
3. Build with Bubblewrap or Android Studio TWA template
`,
    },
  ];
}
