/**
 * Permanent 40-category competitive scoreboard (DreamOS86 vs Lovable vs Base44).
 * Scores are capped by evidence rules in dreamos-readiness-score.ts — never inflate to 100.
 */

export type CompetitiveCategoryId =
  | "prompt_app_creation"
  | "question_vs_build_intent"
  | "blueprint_quality"
  | "create_workflow_ui"
  | "template_system"
  | "style_presets"
  | "generated_ui_quality"
  | "backend_generation_quality"
  | "database_supabase_depth"
  | "auth_security_depth"
  | "credit_cost_transparency"
  | "provider_cost_control"
  | "profit_protection_3x"
  | "multi_model_routing"
  | "prompt_compression_cache"
  | "editor_workspace"
  | "file_tree_tabs"
  | "ai_diff_review"
  | "checkpoints_rollback"
  | "app_dashboard"
  | "app_lifecycle_states"
  | "stale_build_recovery"
  | "preview_system"
  | "publish_system"
  | "subdomain_public_url"
  | "vercel_deploy_system"
  | "public_p_slug_rendering"
  | "admin_dashboard"
  | "billing_admin_economics"
  | "logs_diagnostics"
  | "error_handling"
  | "mobile_responsiveness"
  | "production_safety"
  | "missing_id_protection"
  | "placeholder_prevention"
  | "testing_verify_coverage"
  | "overall_polish"
  | "end_user_trust"
  | "founder_admin_control"
  | "real_production_readiness";

export type CompetitorBenchmarkSource = "measured" | "estimated" | "not_verified";

export type CompetitiveCategoryDef = {
  id: CompetitiveCategoryId;
  index: number;
  title: string;
  evidencePaths: string[];
  verifyCommands: string[];
  e2eSpec?: string;
  dreamosBaseScore: number;
  lovableScore: number;
  base44Score: number;
  lovableSource: CompetitorBenchmarkSource;
  base44Source: CompetitorBenchmarkSource;
  fixToReach100: string;
};

export const COMPETITIVE_CATEGORIES: CompetitiveCategoryDef[] = [
  {
    id: "prompt_app_creation",
    index: 1,
    title: "Prompt → app creation",
    evidencePaths: [
      "src/app/api/projects/create-from-prompt/route.ts",
      "src/lib/projects/create-project-from-prompt.ts",
      "src/lib/ai/preflight-server.ts",
    ],
    verifyCommands: ["npm run verify:create-flow", "npm run test:e2e -- single-create-funnel"],
    e2eSpec: "tests/e2e/single-create-funnel.spec.ts",
    dreamosBaseScore: 82,
    lovableScore: 88,
    base44Score: 82,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "E2E: one prompt → project row → dashboard → builder with stable projectId.",
  },
  {
    id: "question_vs_build_intent",
    index: 2,
    title: "Question vs build intent handling",
    evidencePaths: ["src/lib/intent/create-intent-classifier.ts", "src/lib/ai/preflight-server.ts"],
    verifyCommands: ["npm run verify:intent-gate", "npm run test:e2e -- question-intent"],
    e2eSpec: "tests/e2e/question-intent.spec.ts",
    dreamosBaseScore: 82,
    lovableScore: 75,
    base44Score: 72,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "E2E proves no project/credits for question_only; log intent metrics.",
  },
  {
    id: "blueprint_quality",
    index: 3,
    title: "Blueprint quality",
    evidencePaths: [
      "src/lib/build/app-blueprint.ts",
      "src/lib/build/blueprint-archetypes.ts",
      "src/lib/build/blueprint-scoring.ts",
      "src/lib/build/blueprint-deterministic.ts",
      "src/app/api/build/blueprint/route.ts",
    ],
    verifyCommands: ["npm run verify:blueprint", "npm run verify:generation", "npm run test:e2e -- blueprint-approval"],
    e2eSpec: "tests/e2e/blueprint-approval.spec.ts",
    dreamosBaseScore: 84,
    lovableScore: 85,
    base44Score: 80,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "50-prompt benchmark + blueprint score avg >=85 on live runs.",
  },
  {
    id: "create_workflow_ui",
    index: 4,
    title: "Create page workflow UI",
    evidencePaths: [
      "src/components/create/premium-create-funnel.tsx",
      "src/lib/create/create-flow-state.ts",
      "src/hooks/use-create-flow.ts",
    ],
    verifyCommands: ["npm run verify:create-flow", "npm run test:e2e -- single-create-funnel"],
    e2eSpec: "tests/e2e/single-create-funnel.spec.ts",
    dreamosBaseScore: 82,
    lovableScore: 92,
    base44Score: 85,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Live E2E full funnel + mobile QA at 375–768px.",
  },
  {
    id: "template_system",
    index: 5,
    title: "Template system",
    evidencePaths: [
      "src/lib/templates/template-catalog.ts",
      "src/lib/templates/template-archetypes.ts",
      "src/lib/templates/template-blueprints.ts",
      "src/lib/templates/template-data-models.ts",
      "src/lib/templates/template-file-plans.ts",
      "src/app/(app)/templates/page.tsx",
    ],
    verifyCommands: ["npm run verify:templates", "npm run verify:create-flow"],
    dreamosBaseScore: 82,
    lovableScore: 90,
    base44Score: 82,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Prove template influence on blueprint + live benchmark per template.",
  },
  {
    id: "style_presets",
    index: 6,
    title: "Style presets",
    evidencePaths: [
      "src/lib/create/style-presets.ts",
      "src/app/api/build/blueprint/route.ts",
      "src/lib/create/create-flow-config.ts",
    ],
    verifyCommands: ["npm run verify:create-flow", "npm run test:e2e -- create-style-template-tier"],
    e2eSpec: "tests/e2e/create-style-template-tier.spec.ts",
    dreamosBaseScore: 78,
    lovableScore: 80,
    base44Score: 75,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Prove preset in blueprint metadata + benchmark sample apps.",
  },
  {
    id: "generated_ui_quality",
    index: 7,
    title: "Generated UI quality",
    evidencePaths: [
      "src/lib/generation/generated-ui-review.ts",
      "src/lib/generation/ui-quality-spec.ts",
      "src/lib/generation/app-type-ui-requirements.ts",
      "benchmarks/prompts/live-smoke.json",
    ],
    verifyCommands: ["npm run verify:ui-quality", "npm run benchmark:score"],
    dreamosBaseScore: 72,
    lovableScore: 90,
    base44Score: 82,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Run 50-prompt benchmark; placeholder rate <5%; build success >90%.",
  },
  {
    id: "backend_generation_quality",
    index: 8,
    title: "Backend generation quality",
    evidencePaths: [
      "src/lib/build/build-pipeline.ts",
      "src/lib/build/backend-plan.ts",
      "src/lib/build/blueprint-deterministic.ts",
    ],
    verifyCommands: ["npm run verify:backend-generation", "npm run verify:generation", "npm run benchmark:score"],
    dreamosBaseScore: 82,
    lovableScore: 82,
    base44Score: 78,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Live benchmark backend plan completeness >=80% when backend needed.",
  },
  {
    id: "database_supabase_depth",
    index: 9,
    title: "Database/Supabase depth",
    evidencePaths: [
      "src/lib/build/database-depth-plan.ts",
      "src/lib/build/backend-plan.ts",
      "src/app/api/projects/[id]/integrations/supabase",
    ],
    verifyCommands: ["npm run verify:database-depth", "npm run verify:auth"],
    dreamosBaseScore: 80,
    lovableScore: 78,
    base44Score: 75,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "E2E connect-user-project Supabase flow + RLS on generated schema plans.",
  },
  {
    id: "auth_security_depth",
    index: 10,
    title: "Auth/security depth",
    evidencePaths: ["src/lib/auth", "supabase/migrations"],
    verifyCommands: ["npm run verify:auth", "npm run verify:security"],
    dreamosBaseScore: 75,
    lovableScore: 85,
    base44Score: 78,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "verify:rls + pen-test checklist artifact.",
  },
  {
    id: "credit_cost_transparency",
    index: 11,
    title: "Credit/cost transparency",
    evidencePaths: ["src/lib/billing/pricing-config.ts", "src/app/api/credits/quote/route.ts"],
    verifyCommands: ["npm run verify:billing"],
    dreamosBaseScore: 88,
    lovableScore: 45,
    base44Score: 50,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "E2E quote visible before every paid operation.",
  },
  {
    id: "provider_cost_control",
    index: 12,
    title: "Provider cost control",
    evidencePaths: ["src/lib/ai/cost-budget.ts", "src/lib/ai/model-cost-runtime.ts"],
    verifyCommands: ["npm run verify:model-cost-optimizer"],
    dreamosBaseScore: 85,
    lovableScore: 60,
    base44Score: 60,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Live budget tracker per operation in admin + audits.",
  },
  {
    id: "profit_protection_3x",
    index: 13,
    title: "3× profit protection",
    evidencePaths: ["src/lib/billing/pricing-config.ts", "src/lib/billing/credit-profit-guard.ts"],
    verifyCommands: ["npm run verify:billing"],
    dreamosBaseScore: 92,
    lovableScore: 40,
    base44Score: 40,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Audit all charge paths bypassing guard.",
  },
  {
    id: "multi_model_routing",
    index: 14,
    title: "Multi-model routing",
    evidencePaths: [
      "src/lib/ai/model-router.ts",
      "src/lib/ai/model-cost-runtime.ts",
      "src/lib/ai/route-decision-log.ts",
    ],
    verifyCommands: ["npm run verify:model-cost-optimizer", "npm run verify:wiring"],
    dreamosBaseScore: 82,
    lovableScore: 85,
    base44Score: 80,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Admin route decision audit + live escalation evidence on complex builds.",
  },
  {
    id: "prompt_compression_cache",
    index: 15,
    title: "Prompt compression/cache",
    evidencePaths: ["src/lib/ai/prompt-compressor.ts", "src/lib/ai/generation-cache.ts"],
    verifyCommands: ["npm run verify:generation"],
    dreamosBaseScore: 80,
    lovableScore: 70,
    base44Score: 65,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Measure cache hit rate in benchmark report.",
  },
  {
    id: "editor_workspace",
    index: 16,
    title: "Editor workspace",
    evidencePaths: [
      "src/components/builder/app-builder-workspace.tsx",
      "src/lib/editor/editor-session.ts",
      "scripts/verify-editor.mjs",
    ],
    verifyCommands: ["npm run verify:editor", "npm run test:e2e -- builder-diff"],
    e2eSpec: "tests/e2e/builder-diff.spec.ts",
    dreamosBaseScore: 75,
    lovableScore: 88,
    base44Score: 82,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "E2E builder-diff full flow.",
  },
  {
    id: "file_tree_tabs",
    index: 17,
    title: "File tree/tabs",
    evidencePaths: [
      "src/components/editor/file-tree.tsx",
      "src/components/editor/editor-tabs.tsx",
      "src/lib/editor/file-tree-build.ts",
    ],
    verifyCommands: ["npm run verify:editor", "npm run test:e2e -- builder-diff"],
    e2eSpec: "tests/e2e/builder-diff.spec.ts",
    dreamosBaseScore: 82,
    lovableScore: 85,
    base44Score: 80,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "E2E open file + tab switch on 50+ files project.",
  },
  {
    id: "ai_diff_review",
    index: 18,
    title: "AI diff review",
    evidencePaths: [
      "src/components/editor/ai-diff-viewer.tsx",
      "src/app/api/editor/pending-diff/route.ts",
      "src/app/api/editor/apply-diff/route.ts",
    ],
    verifyCommands: ["npm run verify:editor", "npm run test:e2e -- builder-diff"],
    e2eSpec: "tests/e2e/builder-diff.spec.ts",
    dreamosBaseScore: 72,
    lovableScore: 80,
    base44Score: 75,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "E2E reject/accept diff with checkpoint.",
  },
  {
    id: "checkpoints_rollback",
    index: 19,
    title: "Checkpoints/rollback",
    evidencePaths: [
      "src/app/api/editor/checkpoints/route.ts",
      "src/components/editor/checkpoint-timeline.tsx",
      "src/lib/editor/checkpoints.ts",
    ],
    verifyCommands: ["npm run verify:editor", "npm run test:e2e -- builder-diff"],
    e2eSpec: "tests/e2e/builder-diff.spec.ts",
    dreamosBaseScore: 65,
    lovableScore: 82,
    base44Score: 70,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "E2E rollback restores file content.",
  },
  {
    id: "app_dashboard",
    index: 20,
    title: "App dashboard / Your Apps",
    evidencePaths: [
      "src/app/api/projects/route.ts",
      "src/components/apps/projects-view.tsx",
      "src/components/create/workspace/app-dashboard-panel.tsx",
      "src/lib/import/zip-import-service.ts",
      "src/app/api/projects/import-zip/route.ts",
    ],
    verifyCommands: ["npm run verify:create-flow", "npm run verify:zip-import", "npm run test:e2e -- zip-import"],
    e2eSpec: "tests/e2e/zip-import.spec.ts",
    dreamosBaseScore: 84,
    lovableScore: 88,
    base44Score: 82,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Live E2E immediate list after create; publish URL visible when live.",
  },
  {
    id: "app_lifecycle_states",
    index: 21,
    title: "App lifecycle states",
    evidencePaths: ["src/lib/projects/project-lifecycle.ts", "src/app/api/projects/[id]/status/route.ts"],
    verifyCommands: ["npm run verify:project-lifecycle"],
    dreamosBaseScore: 85,
    lovableScore: 70,
    base44Score: 68,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "E2E every transition path + failure states.",
  },
  {
    id: "stale_build_recovery",
    index: 22,
    title: "Stale build recovery",
    evidencePaths: ["src/lib/build/reconcile-project-build.ts", "src/lib/projects/reconcile-lifecycle.ts"],
    verifyCommands: ["npm run test:e2e -- dashboard-lifecycle"],
    dreamosBaseScore: 82,
    lovableScore: 75,
    base44Score: 72,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "E2E stale building → generated when files exist.",
  },
  {
    id: "preview_system",
    index: 23,
    title: "Preview system",
    evidencePaths: [
      "src/lib/preview/preview-provider-registry.ts",
      "src/lib/preview/preview-build-service.ts",
      "src/app/api/projects/[id]/preview/start/route.ts",
      "src/components/preview/preview-status-panel.tsx",
      "src/components/repair/repair-center.tsx",
    ],
    verifyCommands: ["npm run verify:preview", "npm run verify:preview-providers", "npm run verify:repair"],
    e2eSpec: "tests/e2e/preview-runtime.spec.ts",
    dreamosBaseScore: 82,
    lovableScore: 95,
    base44Score: 85,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Live preview E2E: generate → start session → /preview/{id} loads; Vercel hosted when connected.",
  },
  {
    id: "publish_system",
    index: 24,
    title: "Publish system",
    evidencePaths: [
      "src/lib/publish/publish-service.ts",
      "src/lib/publish/publish-versioning.ts",
      "src/app/api/projects/[id]/publish/route.ts",
      "src/components/publish/public-app-renderer.tsx",
      "src/components/publish/publish-status-panel.tsx",
    ],
    verifyCommands: ["npm run verify:publish", "npm run verify:repair"],
    e2eSpec: "tests/e2e/failure-repair.spec.ts",
    dreamosBaseScore: 82,
    lovableScore: 90,
    base44Score: 85,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "E2E publish + unpublish + version v2 + rollback.",
  },
  {
    id: "subdomain_public_url",
    index: 25,
    title: "Subdomain/public URL system",
    evidencePaths: [
      "src/lib/publish/public-url.ts",
      "src/lib/publish/subdomain.ts",
      "src/components/publish/public-url-mode-badge.tsx",
      "scripts/verify-dns-wildcard.mjs",
    ],
    verifyCommands: ["npm run verify:publish", "npm run verify:dns-wildcard"],
    dreamosBaseScore: 65,
    lovableScore: 92,
    base44Score: 88,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Live DNS verify artifact when wildcard enabled.",
  },
  {
    id: "vercel_deploy_system",
    index: 26,
    title: "Vercel/deploy system",
    evidencePaths: [
      "src/lib/deploy/vercel-config.ts",
      "src/lib/deploy/vercel-connection.ts",
      "src/app/api/deploy/vercel/start/route.ts",
      "src/components/deploy/deploy-workspace-panel.tsx",
      "scripts/deploy-tests.ts",
    ],
    e2eSpec: "tests/e2e/deploy-vercel.spec.ts",
    verifyCommands: ["npm run verify:deploy"],
    dreamosBaseScore: 62,
    lovableScore: 88,
    base44Score: 80,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "User OAuth connect + E2E with test token.",
  },
  {
    id: "public_p_slug_rendering",
    index: 27,
    title: "Public /p/[slug] app rendering",
    evidencePaths: ["src/lib/publish/published-renderer.ts", "src/app/p/[slug]/page.tsx"],
    verifyCommands: ["npm run verify:publish", "npm run test:e2e -- publish-public-url"],
    dreamosBaseScore: 58,
    lovableScore: 90,
    base44Score: 82,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Published renderer E2E + multi-page snapshot nav.",
  },
  {
    id: "admin_dashboard",
    index: 28,
    title: "Admin dashboard",
    evidencePaths: ["src/components/admin/admin-view.tsx", "src/app/(app)/admin"],
    verifyCommands: ["npm run verify:health"],
    dreamosBaseScore: 82,
    lovableScore: 50,
    base44Score: 55,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Competitive score tab integrated + alerts.",
  },
  {
    id: "billing_admin_economics",
    index: 29,
    title: "Billing/admin economics",
    evidencePaths: ["src/app/api/admin/credit-economy/route.ts"],
    verifyCommands: ["npm run verify:billing"],
    dreamosBaseScore: 88,
    lovableScore: 35,
    base44Score: 40,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Stripe prod E2E + margin alert automation.",
  },
  {
    id: "logs_diagnostics",
    index: 30,
    title: "Logs/diagnostics",
    evidencePaths: ["src/app/api/diagnostics/ingest/route.ts", "src/app/api/admin/runtime-diagnostics-bundle/route.ts"],
    verifyCommands: ["npm run verify:health"],
    dreamosBaseScore: 75,
    lovableScore: 60,
    base44Score: 55,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Preview/publish logs in UI + export bundle.",
  },
  {
    id: "error_handling",
    index: 31,
    title: "Error handling",
    evidencePaths: [
      "src/lib/ids/required-ids.ts",
      "src/components/repair/repair-center.tsx",
      "src/lib/repair/run-user-ai-repair.ts",
      "scripts/verify-repair.mjs",
    ],
    verifyCommands: ["npm run verify:repair", "npm run verify:ids"],
    e2eSpec: "tests/e2e/failure-repair.spec.ts",
    dreamosBaseScore: 82,
    lovableScore: 85,
    base44Score: 78,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Live E2E for each failure type + refund proof.",
  },
  {
    id: "mobile_responsiveness",
    index: 32,
    title: "Mobile responsiveness",
    evidencePaths: [
      "src/components/create/premium-create-funnel.tsx",
      "src/components/apps/projects-view.tsx",
      "src/components/builder/app-builder-workspace.tsx",
      "scripts/verify-mobile-layout.mjs",
    ],
    verifyCommands: ["npm run verify:mobile-layout", "npm run test:e2e -- mobile-layout"],
    e2eSpec: "tests/e2e/mobile-layout.spec.ts",
    dreamosBaseScore: 65,
    lovableScore: 88,
    base44Score: 82,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Playwright mobile viewport pass all core routes.",
  },
  {
    id: "production_safety",
    index: 33,
    title: "Production safety",
    evidencePaths: [
      "scripts/verify-production-hardening.mjs",
      "src/lib/security/route-guard.ts",
      "src/lib/security/rate-limit.ts",
      "src/lib/security/audit-events.ts",
    ],
    verifyCommands: [
      "npm run verify:production-hardening",
      "npm run verify:security",
      "npm run verify:mutation-guards",
    ],
    e2eSpec: "tests/e2e/failure-repair.spec.ts",
    dreamosBaseScore: 88,
    lovableScore: 75,
    base44Score: 72,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Remove OS-level TLS=0; prod fail on TLS disable.",
  },
  {
    id: "missing_id_protection",
    index: 34,
    title: "Missing ID protection",
    evidencePaths: ["src/lib/ids/api-mutation-guard.ts"],
    verifyCommands: ["npm run verify:ids", "npm run verify:security"],
    dreamosBaseScore: 72,
    lovableScore: 70,
    base44Score: 68,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "verify:security lists every mutation route guarded.",
  },
  {
    id: "placeholder_prevention",
    index: 35,
    title: "Placeholder/fake app prevention",
    evidencePaths: ["src/lib/build/generated-app-validator.ts", "src/lib/build/complete-build-with-validation.ts"],
    verifyCommands: ["npm run test:e2e -- no-placeholder-app"],
    e2eSpec: "tests/e2e/no-placeholder-app.spec.ts",
    dreamosBaseScore: 82,
    lovableScore: 80,
    base44Score: 75,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Benchmark placeholder rate <5%.",
  },
  {
    id: "testing_verify_coverage",
    index: 36,
    title: "Testing/verify coverage",
    evidencePaths: ["scripts/verify-all.mjs", "tests/e2e"],
    verifyCommands: ["npm run verify:all", "npm run verify:e2e"],
    dreamosBaseScore: 70,
    lovableScore: 85,
    base44Score: 78,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "verify:e2e green in CI; benchmark artifact committed.",
  },
  {
    id: "overall_polish",
    index: 37,
    title: "Overall polish",
    evidencePaths: [
      "src/components/create/premium-create-funnel.tsx",
      "src/components/apps/projects-view.tsx",
      "src/components/builder/app-builder-workspace.tsx",
      "scripts/verify-mobile-layout.mjs",
    ],
    verifyCommands: ["npm run verify:mobile-layout", "npm run test:e2e -- mobile-layout"],
    e2eSpec: "tests/e2e/mobile-layout.spec.ts",
    dreamosBaseScore: 72,
    lovableScore: 92,
    base44Score: 85,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Design pass + Lighthouse on create/builder.",
  },
  {
    id: "end_user_trust",
    index: 38,
    title: "End-user trust",
    evidencePaths: [
      "src/lib/publish/publish-config.ts",
      "src/components/create/create-credit-estimate.tsx",
      "src/components/repair/repair-center.tsx",
    ],
    verifyCommands: ["npm run verify:e2e", "npm run verify:repair"],
    e2eSpec: "tests/e2e/failure-repair.spec.ts",
    dreamosBaseScore: 82,
    lovableScore: 90,
    base44Score: 82,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "All honest states E2E; no fake ready/published.",
  },
  {
    id: "founder_admin_control",
    index: 39,
    title: "Founder/admin control",
    evidencePaths: ["src/app/api/admin/credit-economy/route.ts", "src/app/api/admin/competitive-score/route.ts"],
    verifyCommands: ["npm run verify:competitive-score"],
    dreamosBaseScore: 88,
    lovableScore: 40,
    base44Score: 45,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "Automated margin alerts + weekly benchmark cron.",
  },
  {
    id: "real_production_readiness",
    index: 40,
    title: "Real production readiness",
    evidencePaths: ["scripts/verify-all.mjs", "scripts/verify-repair.mjs"],
    verifyCommands: ["npm run verify:all", "npm run verify:repair"],
    e2eSpec: "tests/e2e/failure-repair.spec.ts",
    dreamosBaseScore: 72,
    lovableScore: 90,
    base44Score: 82,
    lovableSource: "estimated",
    base44Source: "estimated",
    fixToReach100: "verify:all + verify:e2e + benchmark gates all green.",
  },
];

export function getCategoryById(id: CompetitiveCategoryId): CompetitiveCategoryDef | undefined {
  return COMPETITIVE_CATEGORIES.find((c) => c.id === id);
}
